on:
  push:
    branches:
     - main
     # - master
     # - rc-**
     # - pkgdown/**
  # pull_request:
  #   branches:
  #    - main
  #    - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r-dependencies@v1
        # with:
        #   needs: website

      # TODO: remove this when https://github.com/r-lib/actions/issues/386 is fixed
      - name: Install website dependencies
        shell: Rscript {0}
        run: |
          needs <- pak::local_dev_deps(dependencies = "Config/Needs/website")[["ref"]]
          if (Sys.info()[["sysname"]] == "Linux") {
            for (dep in needs) {
              pak::pkg_system_requirements(dep, execute = TRUE)
            }
          }
          pak::pkg_install(needs)

      - name: Build Site
        shell: Rscript {0}
        run: |
          pkgdown::build_site(new_process = FALSE)

      - name: Validate all topics exist (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        env:
          R_CLI_NUM_COLORS: 1
        run: |
          pkgdown::build_reference_index()
          if (length(warnings()) > 0) {
            cat(
              "::warning title=pkgdown reference index::",
              paste(capture.output(warnings()), collapse = "%0A"),
              sep = ""
            )
            if ("${{ github.event_name }}" != "push") {
              stop("pkgdown reference index is missing topics")
            }
          }

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
