on:
  push:
    branches:
     - main
     # - master
     # - rc-**
     # - pkgdown/**
  # pull_request:
  #   branches:
  #    - main
  #    - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      # TODO: remove this when https://github.com/r-lib/actions/issues/386 is fixed
      - uses: r-lib/actions/setup-r-dependencies@v1

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          needs: |
            website

      - name: Build Site
        shell: Rscript {0}
        run: |
          pkgdown::build_site(new_process = FALSE)

      # Must validate after. Otherwise files are saved and `pkgdown::build_site()` gets mad
      - name: Validate all topics exist (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          pkgdown::build_reference_index()
          stopifnot(length(warnings()) == 0)

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
